spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://192.168.241.3:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  rabbitmq:
    host: 192.168.241.3
    port: 5672    
env:
  hello
